name: proxy-experiments

services:
  # OpenResty is essentialy nginx with lua support
  openresty:
    image: openresty/openresty:jammy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  # a simple dummy API w/ single endpoint that returns the client's IP (together with the service's name, passed via env)
  api1:
    build:
      context: api-server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NAME=api-server-1
    # expose the port to the host machine
    ports:
      - 3000:3000
  # another instance of the same dummy API
  api2:
    build:
      context: api-server
      dockerfile: Dockerfile
    environment:
      - NAME=api-server-2
      # NOTE: passing the same port as above works because within the Docker compose network, every service is its own machine with its own hostname and ports
      - PORT=3000
    # expose the port to the host machine on port 3001
    ports:
      - 3001:3000
    